[package]
name = "dogsoap"
version = "5.0.0-alpha.3"
edition = "2024"
description = "Data-Oriented, Simple, Goal-Oriented Action Planning"
license = "MIT OR Apache-2.0"
categories = ["games", "game-development"]
keywords = ["goap", "dogoap", "ai"]
repository = "https://github.com/AmyGilhespy/dogsoap"

[dependencies]
dashmap = { version = "6.2.1", optional = true }
fasteval = { version = "0.2.4", optional = true }
hashbrown = { version = "0.17.1", optional = true, features = ["serde"] }
nanoserde = { version = "0.2.1", optional = true, default-features = false, features = [
	"ron",
] }
pathfinding = "4.15.0"
serde = { version = "1.0.228", optional = true, features = ["derive"] }
thiserror = "2.0.18"

[features]
default = ["simple", "nanoserde"]
serde = ["dep:serde"]
nanoserde = ["dep:nanoserde"]
simple = ["hashbrown", "dashmap", "fasteval"]
dashmap = ["dep:dashmap"]
fasteval = ["dep:fasteval"]
